"""rsim init — interactive project setup wizard."""

import os
import sys


def register(subparsers):
    p = subparsers.add_parser("init", help="Initialize a new project configuration")
    p.add_argument("project", nargs="?", help="Project name (interactive if omitted)")
    p.add_argument("--non-interactive", action="store_true", help="Non-interactive mode (use env vars)")


def run(args, config):
    from core.config import list_projects
    from core.tui import styled

    # Interactive wizard
    project = _prompt_project_name(args.project)
    if not project:
        print("Error: Project name is required.")
        return 1

    # Check if project already exists
    existing = list_projects()
    if project in existing:
        if not _confirm(f"Project '{project}' already exists. Overwrite?"):
            print("Cancelled.")
            return 0

    print()
    print(styled.title(f"Initializing project: {project}"))
    print()

    # Collect configuration
    project_root = _prompt("Project root directory (e.g., C:/BYD_OVS_CB)",
                           default="C:/BYD_OVS_CB")

    binding = _prompt("Binding name", default="ovrs25")

    build_config = _prompt("Build config name (for R2D2)",
                           default="ROS_PER_SIT_RPM_FCT_RECR")

    # Asset paths
    r2d2_script = _prompt("R2D2.py path",
                          default=os.path.join(project_root, "apl", "base", "tools", "build", "R2D2.py"))

    assets_dir = _prompt("Assets directory (runtime XML, config templates)",
                         default=os.path.join(project_root, "assets"))

    hex_build_script = _prompt("HEX build script path",
                               default=os.path.join(project_root, "apl", "byd", "bindings",
                                                    binding, "buildscripts", "testbuild_BaseC0S_SINGLE.bat"))

    selena_build_script = _prompt("Selena build script path",
                                  default=os.path.join(project_root, "apl", "byd", "bindings",
                                                       binding, "buildscripts", "jenkins_selena_build.bat"))

    # Environment
    boost_root = _prompt("BOOST_ROOT", default="C:/local/boost_1_63_0")
    python3_path = _prompt("Python3 path", default="C:/local/Python37-32/python.exe")
    matlab_root = _prompt("MATLAB root", default="C:/Program Files/MATLAB/R2023b")

    print()
    print("Summary:")
    print(f"  Project: {project}")
    print(f"  Root:    {project_root}")
    print(f"  Binding: {binding}")
    print(f"  R2D2:    {r2d2_script}")
    print(f"  Boost:   {boost_root}")

    if not _confirm("\nCreate this configuration?"):
        print("Cancelled.")
        return 0

    # Create config
    from core.config import get_projects_dir
    projects_dir = get_projects_dir()
    proj_dir = os.path.join(projects_dir, project)
    os.makedirs(proj_dir, exist_ok=True)

    # Write config.yaml
    config_data = f"""\
# Project: {project}
# Generated by rsim init

project:
  name: "{project}"
  platform: "gen5_selena"

paths:
  project_root: "{project_root}"
  binding: "{binding}"
  r2d2_script: "{r2d2_script}"
  build_config: "{build_config}"
  hex_build_script: "{hex_build_script}"
  selena_build_script: "{selena_build_script}"
  assets_dir: "{assets_dir}"

environment:
  boost_root: "{boost_root}"
  python3_path: "{python3_path}"
  matlab_root: "{matlab_root}"

# Default signals — edit or add config/projects/{project}/signals.yaml
analysis:
  default_signals:
    - name: "FCTA_State"
      group: "fcta"
      description: "FCTA 状态机"
    - name: "FCTA_Obj_Distance"
      group: "fcta"
      description: "目标距离"
    - name: "TGU_Distance"
      group: "tgu"
      description: "TGU 距离"
    - name: "TGU_Angle"
      group: "tgu"
      description: "TGU 角度"

# Default rules — edit or add config/projects/{project}/rules.yaml
rules:
  - name: "fcta_activates"
    signal: "FCTA_State"
    condition: "reaches value 1"
    severity: "P0"
    description: "FCTA should enter ACTIVE state"
  - name: "no_log_errors"
    source: "log"
    condition: "no [ERROR]"
    severity: "P1"
    description: "Simulation log should have no errors"
"""

    config_path = os.path.join(proj_dir, "config.yaml")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(config_data)

    # Create assets subdirectory
    assets_path = os.path.join(proj_dir, "assets")
    os.makedirs(assets_path, exist_ok=True)

    readme = f"""# Assets for {project}

Place simulation assets here:
- `runtime/*.xml` — runtime XML files
- `configs/*.txt` — config templates
- `templates/*.mf4` — reference MF4 files

These are referenced by `config.yaml` paths.
"""
    with open(os.path.join(assets_path, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme)

    print()
    print(styled.ok(f"Project '{project}' initialized!"))
    print()
    print(f"  Config: {config_path}")
    print(f"  Assets: {assets_path}")
    print()
    print("Next steps:")
    print(f"  1. Place runtime XML in {assets_path}/runtime/")
    print(f"  2. Run: rsim --project {project} check")
    print(f"  3. Run: rsim --project {project} build selena")

    return 0


def _prompt(text, default=""):
    """Prompt user for input with default value."""
    if default:
        prompt_str = f"{text} [{default}]: "
    else:
        prompt_str = f"{text}: "

    try:
        value = input(prompt_str).strip()
        return value or default
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(130)


def _prompt_project_name(hint=None):
    """Prompt for project name."""
    if hint:
        return hint
    try:
        return input("Project name: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(130)


def _confirm(text):
    """Yes/no confirmation."""
    try:
        answer = input(f"{text} [y/N]: ").strip().lower()
        return answer in ("y", "yes")
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(130)
